### PR TITLE
Make commands be case-insensitive.

### PR DESCRIPTION
**Pull request by asyncawake**
!HanGMan and !Hangman will now both work.

(https://user-images.githubusercontent.com/37850395/38173315-9e406ee0-35bc-11e8-8f92-b7837616c4d1.JPG)

### CODE REVIEW

**Comment by benrick** [comment]
Don't forget about the `CommandPolicy`, which should also have a comparison in it.

**Comment by asyncawake** [comment]
I tested commands for case sensitivity and my changes did fix it for me (see linked screenshot in my pull request) - simply by adding .ToUpperInvariant() in the CommandHandler.cs  and without changing the command policy.
I haven't figured out how/where would case sensitivity occur if I left the CommandPolicy unchanged? Just trying to understand how I could test/reproduce a change regarding the CommandPolicy. Again, for me the commands all seem to be case insensitive already.

**Comment by benrick** [comment]
Yep. Yours gets all uses of it perfectly! The added commands like the `!Magnus` command can only be removed using that casing doing `!RemoveCommand maGNus` will fail (I think).

**Comment by asyncawake** [comment]
I tested that but it works for me. I can add a command like !testcommand and then remove it saying !RemoveCommand teSTcommand.
If I'm not mistaken the debugger showed that every command will eventually be handled through the CommandReceivedHandler method in CommandHandler.cs  where I made my change? Sorry, I'm really trying to wrap my head around this.

**Pull request merged**
